### ISSUE TITLE
IK is really needed.

### ISSUE THREAD

**Issue by j2l** [Nor-s/Anim#23]
**Is your feature request related to a problem? Please describe.**

Hands don't match the video, they should touch each other
![image](https://github.com/user-attachments/assets/44affa38-26c6-4341-afe7-7cbd56e408ca)

**Describe the solution you'd like**
A way to adjust the hand as IK, so the forearm and arm follow the hand

**Describe alternatives you've considered**
None found yet, but welcome to listen to an external solution if it exists.
Blender?

Here's the video https://github.com/user-attachments/assets/99a21b27-f8f8-470d-a978-9e38abb631a4

**Comment by Nor-s** [comment]
@j2l 

hello! I'll add it within a week.

You can also continue your work in Blender using the file > export function.

thank you

**Comment by j2l** [comment]
Perfect @Nor-s thank you!

**Comment by Nor-s** [comment]
![temp](https://github.com/user-attachments/assets/9f5f7089-8659-4e85-a847-a791b7670521)

@j2l 

Wow, this is fun.
I will refine it a little more 🥲

**Comment by j2l** [comment]
Excellent!
