### ISSUE TITLE
Character animation without rig

### ISSUE THREAD

**Issue by elkhalafy** [Nor-s/Anim#25]
Hello 

Can you support Pixar's paper that called character articulation through profile curves ?

This idea for character animation without rigging just based on curves 

Thank you, I hope accept

**Comment by Nor-s** [comment]
@elkhalafy 


hello.

I looked into what you told me, it looks difficult, but it seems worth a try.

I'll try it sometimes. About a year. Because I'm working, I don't have much time. 


Don't expect it to be implemented.
Thank you.

**Comment by elkhalafy** [comment]
Ok, thank you
